awesome-academy/php_intern_emc

database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2020_08_11_115131_create_categories_table.php
database/migrations/2020_08_11_115358_create_products_table.php
database/migrations/2020_08_11_120301_create_ratings_table.php
database/migrations/2020_08_11_120433_create_comments_table.php
database/migrations/2020_08_11_120644_create_orders_table.php
database/migrations/2020_08_11_121433_create_product_orders_table.php
database/migrations/2020_08_11_121853_create_request_products_table.php
database/migrations/2020_08_11_122516_create_foreign_categories_table.php
database/migrations/2020_08_11_123013_create_foreign_products_table.php
database/migrations/2020_08_11_123309_create_foreign_ratings_table.php
database/migrations/2020_08_11_123639_create_foreign_comments_table.php
database/migrations/2020_08_11_124034_create_foreign_orders_table.php
database/migrations/2020_08_11_124226_create_foreign_product_orders_table.php
database/migrations/2020_08_11_124614_create_foreign_request_products_table.php

add tables and relationship with migration

add migration

---

app/Repositories/Eloquent/BaseRepository.php
app/Repositories/Interfaces/RepositoryInterface.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2020_08_11_115131_create_categories_table.php
database/migrations/2020_08_11_115358_create_products_table.php
database/migrations/2020_08_11_120301_create_ratings_table.php
database/migrations/2020_08_11_120433_create_comments_table.php
database/migrations/2020_08_11_120644_create_orders_table.php
database/migrations/2020_08_11_121433_create_product_orders_table.php
database/migrations/2020_08_11_121853_create_request_products_table.php
database/migrations/2020_08_11_122516_create_foreign_categories_table.php
database/migrations/2020_08_11_123013_create_foreign_products_table.php
database/migrations/2020_08_11_123309_create_foreign_ratings_table.php
database/migrations/2020_08_11_123639_create_foreign_comments_table.php
database/migrations/2020_08_11_124034_create_foreign_orders_table.php
database/migrations/2020_08_11_124226_create_foreign_product_orders_table.php
database/migrations/2020_08_11_124614_create_foreign_request_products_table.php
resources/lang/en/common.php

Add repository pattern

---

app/Http/Controllers/HomeController.php
resources/js/scroll.js
resources/lang/en/home.php
resources/sass/home.scss
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/components/header.blade.php
resources/views/components/menu.blade.php
resources/views/components/scroll.blade.php
resources/views/home.blade.php
resources/views/layouts/app.blade.php
routes/web.php
webpack.mix.js

create home static page

---

app/Models/Category.php
app/Models/Comment.php
app/Models/Order.php
app/Models/Product.php
app/Models/Rate.php
app/Models/RequestProduct.php
app/Models/User.php
app/Repositories/Eloquent/BaseRepository.php
app/Repositories/Interfaces/RepositoryInterface.php
resources/lang/en/common.php

add_model_related

---

app/Http/Controllers/Admin/ProductController.php
app/Imports/ImportProducts.php
app/Repositories/Eloquent/ProductRepository.php
app/Repositories/Interfaces/ProductRepositoryInterface.php
composer.json
config/app.php
config/excel.php
config/setting.php
resources/lang/en/admin.php
resources/views/admin/products/add.blade.php
resources/views/welcome.blade.php
routes/web.php
stubs/export.model.stub
stubs/export.plain.stub
stubs/export.query-model.stub
stubs/export.query.stub
stubs/import.collection.stub
stubs/import.model.stub

* Import product to database by csv file

Add_product_by_csv_file

---

app/Http/Controllers/CartController.php
app/helpers.php
config/setting.php
resources/js/cart.js
resources/lang/en/home.php
resources/sass/cart.scss
resources/views/cart.blade.php
resources/views/components/menu.blade.php

Em thực hiện thêm vào giỏ hàng, xóa và update số lượng cộng với kiểm tra số lượng trong database để đưa ra thông báo cho user

add, delete, update cart

---

app/Http/Controllers/Admin/OrderController.php
app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/ProductController.php
app/Models/Order.php
app/Providers/AppServiceProvider.php
app/Repositories/Eloquent/OrderRepository.php
app/Repositories/Interfaces/OrderRepositoryInterface.php
app/Traits/Statusable.php
config/enums.php
resources/js/admin/product.js
resources/lang/en/admin.php
resources/views/admin/orders/edit.blade.php
resources/views/admin/orders/index.blade.php
resources/views/admin/orders/show.blade.php
routes/web.php

add_manage_order

---

app/Http/Controllers/OrderController.php
app/Http/Requests/OrderRequest.php
app/Models/Order.php
app/Models/ProductOrder.php
app/Providers/AppServiceProvider.php
app/Repositories/Eloquent/OrderRepository.php
app/Repositories/Interfaces/OrderRepositoryInterface.php
database/migrations/2020_08_18_122634_add_email_orders.php
resources/js/cart.js
resources/lang/en/home.php
resources/sass/cart.scss
resources/views/cart.blade.php
resources/views/common/cartMessage.blade.php
resources/views/order.blade.php
routes/web.php

order products

---

app/Http/Controllers/Admin/RequestProductController.php
app/Models/RequestProduct.php
app/Providers/RepositoryServiceProvider.php
app/Repositories/Eloquent/RequestProductRepository.php
app/Repositories/Interfaces/RequestProductRepositoryInterface.php
config/app.php
resources/js/admin/product.js
resources/views/admin/requests/add.blade.php
resources/views/admin/requests/index.blade.php
routes/web.php

* Create Manage Request Product

add_manage_request_product

---

.gitignore
app/Http/Controllers/ShopController.php
app/Models/Product.php
app/Repositories/Eloquent/ProductRepository.php
app/Repositories/Interfaces/ProductRepositoryInterface.php
config/setting.php
resources/js/app.js
resources/js/filter_product.js
resources/lang/en/admin.php
resources/sass/shop.scss
resources/views/products/add_request.blade.php
resources/views/shop/index.blade.php
resources/views/shop/product.blade.php
routes/web.php
webpack.mix.js

* Filter Product By category, price, sort, search, discount.

filter_product

---

app/Http/Controllers/OrderController.php
app/Mail/OrderMail.php
resources/lang/en/home.php
resources/views/mails/order.blade.php
routes/web.php

send mail when user order

---

app/Http/Controllers/Admin/CategoryController.php
app/Http/Requests/AdminCategory.php
app/Repositories/Eloquent/CategoryRepository.php
app/Repositories/Interfaces/CategoryRepositoryInterface.php
resources/js/admin/product.js
resources/lang/en/admin.php
resources/views/admin/categories/add.blade.php
resources/views/admin/categories/edit.blade.php
resources/views/admin/categories/index.blade.php
routes/web.php

CRUD category

---

resources/js/app.js
resources/js/share_facebook.js
resources/js/subiz_chat.js
resources/views/layouts/app.blade.php

* add subizchat and facebook share

add_subizchat_and_facebook_share

---

app/Http/Controllers/Admin/UserController.php
app/Http/Requests/UpdateUserRequest.php
app/Repositories/Eloquent/BaseRepository.php
app/Repositories/Eloquent/UserRepository.php
app/Repositories/Interfaces/UserRepositoryInterface.php
config/enums.php
config/setting.php
database/migrations/2020_08_20_071616_add_avatar_user.php
resources/js/admin/product.js
resources/lang/en/admin.php
resources/sass/adminUser.scss
resources/views/admin/layout/head.blade.php
resources/views/admin/layout/main.blade.php
resources/views/admin/users/add.blade.php
resources/views/admin/users/detail.blade.php
resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php
resources/views/admin/users/modelDetail.blade.php
routes/web.php
webpack.mix.js

Thêm, xóa, sửa, xem chi tiết đặt hàng của user

admin user

---

app/Http/Controllers/Admin/RequestProductController.php
app/Http/Controllers/System/NotificationController.php
app/Notifications/RequestProductStatus.php
database/migrations/2020_08_21_043234_create_notifications_table.php
resources/js/admin/product.js
resources/lang/en/admin.php
resources/views/components/notification_order.blade.php
routes/web.php

Create notification request product for guess

notification request product for guess

---

app/Http/Controllers/Admin/RequestProductController.php
app/Http/Requests/CreateRequestProduct.php
app/Models/RequestProduct.php
app/Repositories/Eloquent/CategoryRepository.php
app/Repositories/Eloquent/ProductRepository.php
public/js/app.js
public/mix-manifest.json
resources/js/app.js
resources/sass/shop.scss
resources/views/admin/layout/navbar.blade.php
resources/views/admin/layout/sidebar.blade.php
resources/views/components/menu.blade.php
resources/views/layouts/app.blade.php
resources/views/products/show.blade.php
resources/views/shop/product.blade.php

* complete_project : fix some error.

complete_project

---

app/Http/Requests/CreateReviewRequest.php
app/Repositories/Eloquent/ProductRepository.php
app/Repositories/Eloquent/RequestProductRepository.php
app/Repositories/Interfaces/RequestProductRepositoryInterface.php
public/js/app.js
public/mix-manifest.json
resources/js/admin/datatables-demo.js
resources/js/filter_product.js
resources/views/admin/index.blade.php
resources/views/admin/orders/index.blade.php
resources/views/admin/requests/index.blade.php
resources/views/components/header.blade.php
resources/views/home.blade.php
resources/views/products/productsViewed.blade.php
resources/views/products/show.blade.php

Thêm một vài sửa lỗi nhỏ trên giao diện để hoàn thiện project 1

complete final project 1

---

database/factories/CategoryFactory.php
tests/Unit/CategoryTest.php

Thực hiện test cho model category

unit test model category

---

database/factories/CommentFactory.php
database/factories/OrderFactory.php
database/factories/ProductFactory.php
database/factories/RateFactory.php
database/factories/UserFactory.php
tests/Unit/Models/ProductTest.php

Product_Model_Test

---

database/factories/RequestProduct.php
database/factories/UserFactory.php
tests/Unit/Models/UserTest.php

Unit test user

---

tests/Feature/HomePageTest.php
tests/Feature/LoginPageTest.php

* Create Homepage View Test
* Create Loginpage View Test

test_login_and_homepage_view

---

database/factories/ProductOrder.php
tests/Unit/Models/OrderTest.php
tests/Unit/Models/ProductOrderTest.php

Unit test model Order and Product Order

unit test model Order

---

tests/Unit/CommentTest.php
tests/Unit/RateTest.php
tests/Unit/RequestProductTest.php

* Create Rating model test, Comment model test  RequestProduct model test

unit_test_some_model

---

tests/Feature/ControllerCategory.php

Unit test admin controller category

test admin controller category

---

tests/Feature/Https/Controllers/Admin/ControllerUserTest.php

unit test user controller

---

app/Http/Controllers/OrderController.php
app/Jobs/QueueOrderMail.php
database/migrations/2020_08_31_023250_create_jobs_table.php
tests/Feature/Mail/OrderMailTest.php

Thực hiện gửi mail bằng background job (queue) khi người dùng order sản phẩm

queue send mail when order

---

app/Http/Controllers/Admin/OrderController.php
app/Jobs/SendEmailAcceptOrderJob.php
app/Mail/SendOrderAccepted.php
resources/lang/en/home.php
resources/views/emails/order_accepted.blade.php
tests/Unit/Jobs/SendEmailAcceptOrderJobTest.php

* Sử dụng background job để gửi email cho khách hàng khi admin accepted đơn hàng.

send_mail_accepted_order_background_jobs

---

app/Console/Commands/SendEmailTotalOrderCommand.php
app/Console/Kernel.php
app/Http/Controllers/HomeController.php
app/Mail/SendTotalOrderWeek.php
app/Repositories/Eloquent/OrderRepository.php
app/Repositories/Interfaces/OrderRepositoryInterface.php
config/setting.php
resources/lang/en/home.php
resources/views/emails/total_order_week.blade.php

* Task Schedule for send email to admin about total order from Monday to Friday at every week.

task_schedule_send_email_notify_total_order

---

app/Http/Controllers/Admin/OrderController.php
app/Notifications/OrderStatus.php
resources/lang/en/admin.php
resources/views/components/notification_order.blade.php
tests/Feature/Notifications/NotificationOrderTest.php

Notification for user when admin change status user's order

notification order

---

app/Console/Commands/SendDailyReportOrder.php
app/Console/Kernel.php
app/Mail/DailyReportOrderMail.php
app/Repositories/Eloquent/OrderRepository.php
app/Repositories/Interfaces/OrderRepositoryInterface.php
config/setting.php
resources/lang/en/home.php
resources/views/mails/dailyReportOrder.blade.php
tests/Feature/Mail/DailyReportOrderTest.php

Schedule daily report total orders

schedule daily report order

---

resources/js/cart.js
resources/lang/en/home.php
resources/sass/detail_product.scss
resources/sass/home.scss
resources/sass/shop.scss
resources/views/cart.blade.php
resources/views/components/header.blade.php
resources/views/components/menu.blade.php
resources/views/products/show.blade.php
resources/views/shop/index.blade.php
resources/views/shop/product.blade.php

Update view shop, responsive, fix add cart when filter products

update view shop
